---
- name: Deploy Jenkins
  hosts: build
  become: yes
  become_method: sudo
  become_user: root
  vars:
    jenkins_version: "2.73.1"
    jenkins_url: http://127.0.0.1
    jenkins_port: 8080
    jenkins_install_via: "apt"
    jenkins_jobs: [
        "job",
      ]
      
  roles:
    - emmetog.jenkins
